name       : pipewire
version    : 0.2.4
release    : 5
source     :
    - https://github.com/PipeWire/pipewire/archive/0.2.4.tar.gz : 228487683f4a4553787eecff97276ac4ab6c3cace9ccf6514d1c30904b9b2f57
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libv4l2)
    - pkgconfig(sbc)
    - pkgconfig(x11)
setup      : |
    %meson_configure -Dsystemd=true
build      : |
    %ninja_build
install    : |
    %ninja_install
