name       : pipewire
version    : 0.2.5
release    : 6
source     :
    - https://github.com/PipeWire/pipewire/archive/0.2.5.tar.gz : 6e75bb88a329f97984925bd303643075788df8d51b345bb43feb1be2c3b7102c
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libv4l2)
    - pkgconfig(sbc)
    - pkgconfig(x11)
setup      : |
    %meson_configure -Dsystemd=true
build      : |
    %ninja_build
install    : |
    %ninja_install
