name       : pipewire
version    : 0.3.19
release    : 14
source     :
    - https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/0.3.19/pipewire-0.3.19.tar.bz2 : 67fa2fe7402036bc7a6d5350436fc3e3ce564bdbeadc386ce12bbf101203a77d
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(bluez)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(sbc)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(vulkan)
    - pkgconfig(x11)
    - vulkan-headers
setup      : |
    %meson_configure -Dsystemd=true -Djack=false -Dpipewire-jack=false
build      : |
    %ninja_build
install    : |
    %ninja_install
