name       : pipewire
version    : '0.35'
release    : 16
source     :
    - https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/0.3.25/pipewire-0.3.25.tar.gz : fb6d5a0cbde621659ffd67622f19744dd6c8da8745b060cb1951c3d2045e5166
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(bluez)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(sbc)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(vulkan)
    - pkgconfig(x11)
    - vulkan-headers
setup      : |
    %meson_configure -Dsystemd=enabled -Djack=disabled -Dpipewire-jack=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
