name       : pipewire
version    : 0.1.9
release    : 2
source     :
    - https://github.com/PipeWire/pipewire/archive/0.1.9.tar.gz : d7dc591d60c3544f3c24b2b0ab1db458991dd69d0610337fd0accf136373916b
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libv4l1)
    - pkgconfig(sbc)
    - pkgconfig(x11)
setup      : |
    %meson_configure -Denable_gstreamer=true
build      : |
    %ninja_build
install    : |
    %ninja_install
