name       : pipewire
version    : 0.3.28
release    : 21
source     :
    - https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/0.3.28/pipewire-0.3.28.tar.gz : 1d9271e121a5049aef379e9bb7c50524faa6f971e668806637d7b9df1b7cab88
homepage   : https://pipewire.org/
license    :
    - MIT
    - LGPL-2.1-or-later # libspa-alsa.so
    - GPL-2.0-or-later # libjackserver.so
component  :
    - multimedia.library
    - jack : multimedia.audio
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(avahi-client)
    - pkgconfig32(dbus-1)
    - pkgconfig32(gstreamer-1.0)
    - pkgconfig32(gstreamer-plugins-base-1.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(libpulse)
    - pkgconfig32(libudev)
    - pkgconfig32(ncursesw)
    - pkgconfig32(sdl2)
    - pkgconfig32(sndfile)
    - pkgconfig32(x11)
    - pkgconfig(bluez)
    - pkgconfig(fdk-aac)
    - pkgconfig(jack)
    - pkgconfig(ldacBT-abr)
    - pkgconfig(libavcodec)
    - pkgconfig(libopenaptx)
    - pkgconfig(sbc)
    - vulkan-headers
patterns   :
    - jack :
        - /usr/bin/pw-jack
        - /usr/lib64/pipewire-0.3/jack
        - /usr/lib64/spa-0.2/jack
        - /usr/share/ld.so.conf.d/pipewire-jack.conf
        - /usr/share/pipewire/jack.conf
        - /usr/share/pipewire/media-session.d/with-jack
setup      : |
    patch -Np1 < "${pkgfiles}"/0001-Disable-rtkit-support.patch
    patch -Np1 < "${pkgfiles}"/0002-Let-pipewire-pulse-services-conflict-with-their-puls.patch

    COMMON_OPTIONS="-Dsystemd=enabled \
                    -Dudevrulesdir=%libdir%/udev/rules.d \
                    -Dlibjack-path=%libdir%/pipewire-0.3/jack"

    if [[ -n "${EMUL32BUILD}" ]]; then
        CONFIGURE_OPTIONS="$COMMON_OPTIONS -Dffmpeg=disabled \
                                           -Dbluez5=disabled \
                                           -Dbluez5-codec-aptx=disabled \
                                           -Dbluez5-codec-ldac=disabled \
                                           -Dbluez5-codec-aac=disabled \
                                           -Djack=disabled \
                                           -Dvulkan=disabled"
    else
        CONFIGURE_OPTIONS="$COMMON_OPTIONS -Dffmpeg=enabled"
    fi

    %meson_configure $CONFIGURE_OPTIONS
build      : |
    %ninja_build
install    : |
    %ninja_install
    touch with-alsa
    install -Dm00644 with-alsa $installdir/usr/share/pipewire/media-session.d/
    install -Dm00644 $pkgfiles/pipewire-jack.ld.conf $installdir/usr/share/ld.so.conf.d/pipewire-jack.conf

    # Remove unnecessary udev rules file from the 32-bit package
    if [[ -n "${EMUL32BUILD}" ]]; then
        rm -rf $installdir/%libdir%/udev/
    fi
