name       : pipewire
version    : 0.3.16
release    : 13
source     :
    - https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/0.3.16/pipewire-0.3.16.tar.bz2 : 71a637794ebc7659fc5178059e806a995ebb96b7f8359ed0da20941f85c8cf5e
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(bluez)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(sbc)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(vulkan)
    - pkgconfig(x11)
    - vulkan-headers
setup      : |
    %meson_configure -Dsystemd=true -Djack=false -Dpipewire-jack=false
build      : |
    %ninja_build
install    : |
    %ninja_install
