name       : pipewire
version    : 0.2.2
release    : 3
source     :
    - https://github.com/PipeWire/pipewire/archive/0.2.2.tar.gz : b39773deb79badf951c136505c708d2177b3a4106ecb63e4c063584d5c26d5d7
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libv4l1)
    - pkgconfig(sbc)
    - pkgconfig(x11)
setup      : |
    %meson_configure -Denable_gstreamer=true
build      : |
    %ninja_build
install    : |
    %ninja_install
