name       : pipewire
version    : 0.2.7
release    : 10
source     :
    - https://github.com/PipeWire/pipewire/archive/0.2.7.tar.gz : bfaa0f6ae6c0791e2e0b59234d399753bf24f1b33dbf587682363a8463dd8df1
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(sbc)
    - pkgconfig(x11)
setup      : |
    %meson_configure -Dsystemd=true
build      : |
    %ninja_build
install    : |
    %ninja_install
