name       : pipewire
version    : 0.3.26
release    : 19
source     :
    - https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/0.3.26/pipewire-0.3.26.tar.gz : 05cc9d25de45290c025da5da1b94fc705bddacd93cf3690d0b2988c1ac501ee1
homepage   : https://pipewire.org/
license    : LGPL-2.1-or-later
component  :
    - multimedia.library
    - jack : multimedia.audio
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(bluez)
    - pkgconfig(fdk-aac)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(jack)
    - pkgconfig(ldacBT-abr)
    - pkgconfig(libavcodec)
    - pkgconfig(libopenaptx)
    - pkgconfig(sbc)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(x11)
    - vulkan-headers
patterns   :
    - jack :
        - /usr/bin/pw-jack
        - /usr/lib64/pipewire-0.3/jack
        - /usr/lib64/spa-0.2/jack
        - /usr/share/ld.so.conf.d/pipewire-jack.conf
setup      : |
    %meson_configure \
        -Dffmpeg=enabled \
        -Dsystemd=enabled \
        -Dudevrulesdir=/usr/lib64/udev/rules.d \
        -Dlibjack-path=/usr/lib64/pipewire-0.3/jack
build      : |
    %ninja_build
install    : |
    %ninja_install
    touch with-alsa
    install -Dm00644 with-alsa $installdir/etc/pipewire/media-session.d
    install -Dm00644 $pkgfiles/pipewire-jack.ld.conf $installdir/usr/share/ld.so.conf.d/pipewire-jack.conf
