name       : pipewire
version    : 0.3.25
release    : 18
source     :
    - https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/0.3.25/pipewire-0.3.25.tar.gz : fb6d5a0cbde621659ffd67622f19744dd6c8da8745b060cb1951c3d2045e5166
license    : LGPL-2.1-or-later
component  :
    - multimedia.library
    - jack : multimedia.audio
summary    : Multimedia processing graphs
description: |
    PipeWire is a server and user space API to deal with multimedia pipelines.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(bluez)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(jack)
    - pkgconfig(sbc)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(vulkan)
    - pkgconfig(x11)
    - vulkan-headers
patterns   :
    - jack :
        - /usr/bin/pw-jack
        - /usr/lib64/pipewire-0.3/jack
        - /usr/lib64/spa-0.2/jack
        - /usr/share/ld.so.conf.d/pipewire-jack.conf
setup      : |
    %meson_configure -Dsystemd=enabled -Dudevrulesdir=/usr/lib64/udev/rules.d -Dlibjack-path=/usr/lib64/pipewire-0.3/jack
build      : |
    %ninja_build
install    : |
    %ninja_install
    touch with-alsa
    install -Dm00644 with-alsa $installdir/etc/pipewire/media-session.d
    install -Dm00644 $pkgfiles/pipewire-jack.ld.conf $installdir/usr/share/ld.so.conf.d/pipewire-jack.conf
